# This is a configuration file for Prometheus that tells Prometheus where and how to collect metrics.
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'replisense-backend'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: /metrics
