global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "replisense-backend"
    static_configs:
      - targets: ["host.docker.internal:5000"]
    metrics_path: /metrics

  - job_name: "mcp-server"
    static_configs:
      - targets: ["host.docker.internal:9101"] # Exposed by start_http_server() in MCP
