{
 "title": "Replisense dashboard",
 "tags": [
  "node",
  "express",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "HTTP Status Codes (rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Response Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "rate(http_response_size_bytes_sum[1m])"
    }
   ]
  },
  {
   "title": "Requests by Route",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (path)"
    }
   ]
  },
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Request Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 9, "y": 19 },
   "targets": [
    {
     "expr": "rate(http_request_size_bytes_sum[1m])"
    }
   ]
  }
 ]
}